Runtime/MP1/CMFGame.hpp

This type is actually defined within the `urde::MP1` namespace, not the top-level `urde` namespace. We remove the namespace itself however, given the header for that type is already being included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/29)

MP1/CMFGame: Remove erroneous forward declaration

---

Runtime/GuiSys/CInstruction.cpp

Without this, x20_largestMonoW will never be any value other than zero, which is indicative of a logic bug in the absence of comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/30)

GuiSys/CInstruction: Correct erroneous assignment in TestLargestFont

---

Editor/ProjectManager.cpp

We can just wrap the contents near the label into a lambda function and reuse it as appropriate. While we're at it, we can also get rid of a function pointer cast (and technically undefined behavior).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/35)

Editor/ProjectManager: Remove use of goto

---

Runtime/Weapon/CGameProjectile.cpp
Runtime/Weapon/CGameProjectile.hpp

This has a slightly similar name to FluidFXThink (which has an uppercase X). Given this function isn't explicitly called anywhere directly, this is assumed to be a typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/36)

Runtime/Weapon/CGameProjectile: Fix misnamed virtual function

---

Runtime/CGameOptions.cpp
Runtime/CGameOptions.hpp
Runtime/CGameState.cpp
Runtime/MP1/CFrontEndUI.cpp

Makes the data a little more strongly typed; preventing implicit array->pointer decay. It also allows simplifying assignments within the CGameState code. While we're at it, we can also eliminate several instances of magic numbers related to the array sizes throughout the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/38)

Runtime/CGameOptions: Use std::array where applicable

---

Runtime/Input/CFinalInput.hpp

The other A-prefixed functions all return a float value, however these are truncating float values to bool. We can amend this to prevent potential compilation warnings.
While I was in the area, I noticed the equality operator wasn't const qualified, so I applied the qualifier to it (and provided the trivial inequality operator for logical symmetry).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/37)

Runtime/Input/CFinalInput: Correct return value of AKey, ASpecialKey and AMouseButton

---

Runtime/MP1/CFrontEndUI.cpp
Runtime/MP1/CGBASupport.cpp
Runtime/MP1/COptionsScreen.cpp
Runtime/MP1/CPauseScreen.cpp
Runtime/MP1/CPauseScreenBase.cpp
Runtime/MP1/CQuitGameScreen.cpp
Runtime/MP1/CSaveGameScreen.cpp
Runtime/MP1/MP1.cpp

Provides a more straightforward means of supplying custom behavior in place. Lambdas also typically optimize better compared to std::bind objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/39)

MP1: Migrate from std::bind to lambdas

---

Runtime/RetroTypes.hpp

These are generally used as basic tags and ID types, so these can have a constexpr interface. This is particularly beneficial, given some of these types are used in file-static lookup tables.
Without being constexpr, these type's constructors in that case are technically runtime static constructors. While most compilers will initialize the type at compile-time, this would be dependent on the optimizer. By marking them constexpr, we allow it outright. It also allows those arrays to be made constexpr as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/40)

RetroTypes: Make types constexpr where applicable

---

DataSpec/DNACommon/ANIM.cpp
DataSpec/SpecBase.cpp

Replaces uses of `fprintf` with `fmt::print` where applicable in some debugging code. For trivial character insertion, we can make use of `fputc` instead of `fprintf`, given it's non-formatted text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/44)

RetroDataSpec: Use fmt::print where applicable

---

DataSpec/DNACommon/DNACommon.hpp

These can be replaced with std::strtoull and std::wcstoull, eliminating a platform-specific ifdef.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/45)

DNACommon: Replace platform-specific string conversion functions with standard facilities

---

Runtime/World/CPatterned.hpp

This is incremented within PathFind(), however, because the type within this bitfield is a bool, this can trigger compilation warnings (rightly so). So we can make it a uint32_t to make it obvious that the incrementing behavior is intended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/47)

CPatterned: Correct use of bool in bitfield

---

Runtime/GuiSys/CStringTable.cpp
Runtime/GuiSys/CStringTable.hpp

We can use a std::array instead, avoiding the need for heap allocations, given we can just make the lookup-table constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/49)

CStringTable: Use std::array instead of std::vector

---

Runtime/MP1/CGBASupport.cpp
gbalink/main.cpp

Recent jbus changes have made the interface a little more type-safe. This amends the using code to compile under those changes.
The submodule itself should likely be updated before merging this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/50)

General: Amend relevant code to compile with jbus changes

---

DataSpec/DNACommon/PAK.hpp

Makes the initial value of the members in the default constructor case deterministic, preventing potential uninitialized reads via the member functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/52)

PAK: Zero initialize m_sz and m_pos of PAKEntryReadStream

---

Runtime/Input/ControlMapper.cpp

These should be comparing with >=, not >.
The command table descriptions also weren't kept in sync with the enumeration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/58)

ControlMapper: Prevent array overrun cases

---

visigen/CMakeLists.txt

Instead of using variables, we can directly specify our requirements on the target instance directly. This also avoids modifying CMAKE_CXX_FLAGS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/53)

visigen/CMakeLists: Modify target directly

---

DataSpec/DNAMP1/Tweaks/CTweakPlayerGun.hpp

These arrays are both 5 elements in size. Accessing them at index 5 would be out of bounds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/54)

DNAMP1/CTweakPlayerGun: Prevent array overrun cases

---

DataSpec/DNACommon/WPSC.cpp

This should be calling read() on xunk_SPS1, not xunk_SPS2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/55)

WPSC: Correct typo within WPSM's _read() function

---

Runtime/MP1/World/CFlaahgraTentacle.cpp

This was always using the first element in the array to append t the output joint list, resulting in incorrect names and radius values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/56)

MP1/CFlaahgraTentacle: Amend sphere collision list appending

---

Runtime/World/CScriptDock.cpp
Runtime/World/CScriptDock.hpp
Runtime/World/CScriptPointOfInterest.cpp
Runtime/World/CScriptPointOfInterest.hpp

Based off the use of the const, it's likely that these were intended to be references, rather than be copied by value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/57)

World/CScript*: Pass by reference over by value

---

Runtime/World/CActorModelParticles.cpp

Technically this array wasn't read-only and contained a sequence of modifiable elements. We can make this constexpr so that the compiler can definitively place it into the read-only segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/63)

CActorModelParticles: Make DGRP array constexpr

---

Runtime/Input/CRumbleManager.cpp
Runtime/Input/CRumbleVoice.hpp
Runtime/Input/RumbleFxTable.cpp
Runtime/Input/RumbleFxTable.hpp
Runtime/MP1/CFrontEndUI.cpp
Runtime/MP1/COptionsScreen.cpp

SAdsrData instances are used in a file-scope lookup-table, however, given the constructors aren't constexpr, these instances all technically have a runtime static constructor (from a language point-of-view). We can declare the constructor as constexpr to formally give the compiler leeway to remove them.
This makes the interface of SAdsrDelta constexpr capable as well in order to remain consistent between the two structs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/64)

CRumbleVoice: Make SAdsrData and SAdsrDelta interfaces constexpr

---

Runtime/Audio/CStreamAudioManager.cpp
Runtime/CPakFile.cpp
Runtime/CResLoader.cpp
Runtime/CStringExtras.hpp
Runtime/World/CScriptStreamedMusic.cpp

The strcasecmp and _stricmp functions expect the passed in strings to be null-terminated, however we we're also exposing a std::string_view overload for that function. std::string_view instances aren't required to be null-terminated, so this makes the interface a little unsafe.
We can use std::lexicographical_compare() to provide the same behavior and also properly handle the case of non-null-terminated strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/68)

CStringExtras: Prevent potential out of bounds reads with CompareCaseInsensitive

---

Runtime/CStateManager.cpp
Runtime/World/CEntityInfo.hpp

Allows calling code to potentially avoid copies altogether by moving into the constructor. While we're in the same area, we can eliminate a sign mismatch warning in a loop conditional nearby.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/70)

CEntityInfo: std::move vector in constructor

---

Runtime/World/CMorphBall.cpp
Runtime/World/CPlayer.cpp
Runtime/World/CPlayer.hpp

Allows passing in sizes without potential truncation from size_t, allowing nicer use of std::size() to dehardcode some magic values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/73)

CPlayer: Use size_t with SfxIdFromMaterial

---

Runtime/Collision/CMaterialFilter.cpp
Runtime/Collision/CMaterialFilter.hpp
Runtime/Collision/CMaterialList.hpp

A few instances of CMaterialFilter are constructed at file-scope using the Make* functions and the constructor. Given these aren't constexpr, this means these are technically runtime function calls. We can make these constexpr to allow the initialization to be done at compile-time, slightly improving startup time and eliminating some runtime global constructors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/75)

CMaterialFilter/CMaterialList: Make interface constexpr

---

Runtime/World/CPlayer.cpp

Now that the interface is constexpr, we can mark these as constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/76)

CPlayer: Make file-scope CMaterialFilter instances constexpr

---

Runtime/CPlayerState.cpp
Runtime/CPlayerState.hpp

Makes the arrays strongly-typed. While we're at it, we can make some private class arrays fully implementation details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/77)

CPlayerState: Make use of std::array where applicable

---

Runtime/GuiSys/CGuiWidgetDrawParms.cpp
Runtime/GuiSys/CGuiWidgetDrawParms.hpp

This isn't ever modified, so it can be made const to prevent unintentional modification (and allow it to be placed within the RO segment).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/78)

CGuiWidgetDrawParms: Mark Default instance as const

---

Runtime/GuiSys/CAuiEnergyBarT01.cpp

Without float literals, the calculation is performed in double precision and then truncated down to float implicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/79)

CAuiEnergyBarT01: Prevent truncation within DownloadBarCoordFunc

---

Runtime/Weapon/CBurstFire.cpp
Runtime/Weapon/CBurstFire.hpp
Runtime/World/CScriptGunTurret.cpp
Runtime/World/CScriptGunTurret.hpp

Makes the array type strongly typed and prevents implicit array to pointer decay.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/80)

CBurstFire: Use std::array where applicable

---

Runtime/MP1/CMemoryCardDriver.cpp

In the game executable itself, there exists no fallthrough here (which makes sense, given all IO errors would be reported as character set errors, otherwise).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/83)

CMemoryCardDriver: Correct erroneous fallthrough within HandleCardError

---

Runtime/Graphics/CBooRenderer.cpp

Given the appended types consist of trivial types, it's more efficient in this context to construct the data in place over using push_back, which will cause a redundant copy (move semantics on trivial types are a copy).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/84)

CBooRenderer: Use emplace_back() where applicable

---

Runtime/Camera/CCameraManager.cpp
Runtime/Camera/CCameraManager.hpp

Four of the five variables aren't modified, so they can be specified directly within the functions and just be reused in place of the variable names. This allows the constants to be elided or put into read-only memory if necessary. It also makes the mutable value explicit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/85)

CCameraManager: Collapse private static variables into functions

---

Runtime/MP1/World/CSeedling.cpp
Runtime/MP1/World/CSeedling.hpp

Makes the array contain non-allocating data. This also gets rid of 12 runtime static constructors that would have need to run on program start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/87)

CSeedling: Convert array of std::string to array of std::string_view

---

Runtime/CToken.cpp
Runtime/CToken.hpp
Runtime/IVParamObj.hpp

Allows code gen to be slightly better with CToken (in terms of constructors, the rest of the member functions being noexcept is for consistency).
The move constructor doesn't perform any behavior that would result in an exception being thrown. Marking it as noexcept allows the type to play nicely with facilities that make use of `std::is_move_constructible` to determine whether copies can be avoided or not in certain circumstances during reallocations (e.g. the standard library; notably, std::vector).
We can't mark the move assignment operator as noexcept currently, however, as it calls into interfaces outside of CToken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/89)

{CToken, IVParamObj}: Mark a few interface functions as noexcept where applicable

---

Runtime/MkCastTo.py

Same thing, but less typing, slightly shrinking the file size.
We can also make use of `static_cast` instead of `reinterpret_cast` here, given we check if conversions can be performed with `std::is_convertible` beforehand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/95)

MkCastTo: Use '_v' variants of type traits where applicable

---

Runtime/CIOWin.hpp

No functional change. Just maintains consistency with the rest of the codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/94)

CIOWin: Default the virtual destructor

---

Runtime/Collision/CAABoxFilter.cpp
Runtime/Collision/CAABoxFilter.hpp
Runtime/Collision/CBallFilter.cpp
Runtime/Collision/CBallFilter.hpp
Runtime/Collision/CGameCollision.cpp
Runtime/Collision/CGameCollision.hpp
Runtime/Collision/ICollisionFilter.hpp

With the headers all normalized, we can safely convert the only ICollisionFilter include into a forward declaration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/92)

ICollisionFilter: Use forward declarations where applicable

---

Runtime/Audio/CAudioSys.cpp

Notably, one change eliminates a runtime static constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/91)

CAudioSys: Minor cleanup

---

Runtime/RetroTypes.hpp

These functions/types are quite common throughout the codebase, so making these noexcept allows them to be used within noexcept contexts (or allow contexts to become noexcept).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/90)

RetroTypes: Make functions noexcept where applicable

---

Runtime/Particle/CElementGen.cpp

The game executable checks for a FourCC of ELSC within this function, not SELC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/99)

CElementGen: Correct FourCC in SetTranslation()

---

Runtime/rstl.hpp

Makes the constructors and assignment operators for reserved_vector conditionally noexcept, allowing them to play nicely with standard facilities and avoid needing to copy construct where avoidable if said types don't have throwing constructors/assignment operators. While we're in the same area, we can make minor adjustments to the interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/100)

rstl: Make constructors/assignment operators of reserved_vector conditionally noexcept

---

Runtime/Particle/CIntElement.cpp

Mainly joins together variable declarations and assignments. We can also simplify CIEKeyframeEmitter's GetMaxValue function by making use of `std::max_element`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/101)

CIntElement: Minor clean up

---

Runtime/Particle/CIntElement.cpp
Runtime/Particle/CIntElement.hpp
Runtime/Particle/CParticleDataFactory.cpp

Within the int element handling code, there seems to be a missing implementation (with the FourCC 'RTOI'), which seems to take two 32-bit floating point values, multiplies them, then converts the result to a 32-bit integer.
I've implemented the behavior that the executable performs, though I'm not sure how I'd derive the value to return within `GetMaxValue()`, since this seems to be an urde-specific addition to the vtables (as far as I can tell), and there's no documentation on what it's supposed to do in particular. I don't even think Metroid Prime makes use of the RTOI element (unless I missed it somewhere in a particle script file). Nevertheless, the handling *is* in the executable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

CIntElement: Add class to handle RTOI int elements

---

Runtime/Camera/CBallCamera.cpp

Using a float is very suspect and also more expensive in terms of code-gen to access and modify the variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/107)

CBallCamera: Use bool instead of float for holding boolean value

---

Runtime/Particle/CUVElement.cpp

The game executable initializes the variable being passed into `GetValue()` to `1` before the call. This is likely to ensure that the value is always sane in the event the CIntElement instance doesn't assign anything to the out reference. We can do the same here as well to maintain that guarantee.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/104)

CUVElement: Provide initial value for cv in GetValueUV()

---

Runtime/Collision/CCollidableAABox.cpp
Runtime/Collision/CCollisionPrimitive.hpp

No behavioral changes. Just converts four typedefs into using aliases and defaults the virtual destructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/105)

CCollisionPrimitive: Minor cleanup

---

Runtime/Collision/CCollisionPrimitive.cpp
Runtime/Collision/CCollisionPrimitive.hpp

We can extract the duplicated behavior out into its own member function and then reuse it in order to deduplicate repeated behavior, making for nicer reading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/106)

CCollisionPrimitive: Simplify the InitAdd* member functions

---

Runtime/AutoMapper/CAutoMapper.cpp

Same behavior as the game executable, but without the code duplication per case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/108)

CAutoMapper: Collapse case statements in ProcessMapZoomInput()

---

Runtime/MkCastTo.py

Generates the derived classes with the override specifier to prevent warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/110)

MkCastTo: Use override where applicable

---

Runtime/Weapon/CGunWeapon.cpp
Runtime/Weapon/CGunWeapon.hpp
Runtime/Weapon/CWaveBeam.cpp

Makes use of std::array where applicable, making the types impervious to implicit pointer decay and also making it trivial to eliminate hardcoded loop constants, instead querying the container sizes. This also ensures that the string arrays always end up in read-only memory (given they were still technically mutable).
We can also make a few minor other changes while we're in the same area.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/111)

CGunWeapon: Minor changes

---

Runtime/rstl.hpp

Follows the behavior of the C++17 variant of emplace_back, which returns a reference to the emplaced element. Allows retrieving the reference to the element without needing to query the container for it again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/112)

rstl: Return reference to emplaced element in emplace_back()

---

Runtime/Character/CAnimData.cpp

We can just call the function normally without the need for a const_cast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/115)

CAnimData: Remove usage of const_cast within Touch()

---

Runtime/Character/CParticleGenInfo.cpp
Runtime/Character/CParticleGenInfo.hpp

Allows Intellisense and any other function prototype highlighting features of IDEs to be a little more informative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/116)

CParticleGenInfo: Use slightly more full names for parameters where applicable

---

Runtime/Camera/CCinematicCamera.cpp
Runtime/Character/CAnimData.cpp
Runtime/Character/CParticleDatabase.cpp
Runtime/Character/CPoseAsTransforms.cpp
Runtime/Character/CRagDoll.cpp
Runtime/Character/CSegId.hpp
Runtime/Character/TSegIdMap.hpp
Runtime/Collision/CCollisionActorManager.cpp
Runtime/MP1/World/CFlaahgra.cpp
Runtime/MP1/World/CFlaahgraTentacle.cpp
Runtime/MP1/World/CMetroidBeta.cpp
Runtime/MP1/World/CSpacePirate.cpp
Runtime/MP1/World/CSpankWeed.cpp
Runtime/World/CPatterned.cpp

Makes the interface constexpr compatible, given it only wraps a u8 value. While we're at it, we can use member functions to perform the validity checks so that we don't need to hardcode the magic value indicating an invalid ID in multiple places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/118)

CSegId: Minor changes

---

Runtime/Collision/CCollidableAABox.cpp
Runtime/Collision/CCollidableAABox.hpp
Runtime/Collision/CCollidableCollisionSurface.cpp
Runtime/Collision/CCollidableCollisionSurface.hpp
Runtime/Collision/CCollidableOBBTreeGroup.cpp
Runtime/Collision/CCollidableOBBTreeGroup.hpp
Runtime/Collision/CCollidableSphere.cpp
Runtime/Collision/CCollidableSphere.hpp
Runtime/Collision/CCollisionPrimitive.hpp

We can make these constexpr capable, given they only store primitives and a pointer to a function. This eliminates some static constructors, since the constructors can be elided at compile-time now.
This also completely hides the Type instances from other code, fully making them implementation details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/119)

CollisionPrimitive: Make collision primitive types constexpr capable

---

Runtime/Collision/CCollisionResponseData.cpp
Runtime/Collision/CCollisionResponseData.hpp

Mainly makes use of std::array where applicable, which allows replacing some file-static std::vector instances with constexpr arrays, eliminating some heap allocations.
The remaining other changes are mainly clean-up related.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/120)

CCollisionResponseData: Minor changes

---

Runtime/MP1/World/CNewIntroBoss.cpp

This function actually calls CPatterned's implementation of DoUserAnimEvent(), not CActor's.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/126)

CNewIntroBoss: Correct base class call to DoUserAnimEvent()

---

Runtime/World/CPatterned.cpp

This isn't ever modified, so we can mark it constexpr to eliminate potential runtime initializers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/125)

CPatterned: Mark CMaterialList instance in CollidedWith as constexpr

---

Runtime/Camera/CCameraManager.cpp
Runtime/Camera/CCameraManager.hpp

An unsigned value is passed into RemoveCameraShaker at its only usage spot. This also resolves unsigned/signed comparisons within the function itself. While we're in the same area, we can also collapse the manual lookup into std::find_if.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/127)

CCameraManager:: Resolve signed/unsigned mismatch within RemoveCameraShaker()

---

Runtime/Weapon/CWeaponMode.hpp
Runtime/World/CScriptTrigger.cpp

Given this is such a simple type, this can be made usable with constexpr. This allows the type to be usable at file-scope without potentially incurring a runtime constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/128)

CWeaponMode: Make constexpr capable

---

Runtime/AutoMapper/CAutoMapper.hpp

Makes the signatures a little less ambiguous so that one doesn't need to read the implementation to see what each parameter means. This is particularly nice for IDEs with parameter inspection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/130)

 CAutoMapper: Make SAutoMapperRenderState constructor parameter names more informative

---

Runtime/World/CActor.cpp
Runtime/World/CActor.hpp

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/131)

CActor: Remove top-level const from GetScaledLocatorTransform() and GetLocatorTransform()

---

Runtime/Particle/CRealElement.cpp

This only needs to be called once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/132)

CRealElement: Remove redundant instance() call in CRELifetimeTween::GetValue()

---

Runtime/GuiSys/CTextParser.cpp

This should be prepended with the f suffix to prevent double to float implicit truncation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/133)

CTextParser: Resolve double->float truncation within ParseTag()

---

Runtime/World/CPlayer.cpp

This function actually calls GetPressInput() here, not GetDigitalInput().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/134)

CPlayer: Fix function call mismatch within SidewaysDashAllowed()

---

Runtime/World/CPlayer.cpp

`skDashStrafeDistances` was previously missing the initial element within the array, causing all the elements in the table to be shifted to the over by one. This corrects that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/135)

CPlayer: Add missing element to skDashStrafeDistances

---

Runtime/Graphics/CRainSplashGenerator.cpp

Game code actually uses a constant of `4.0f` as the lower bound for speed, not `0.015625f`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/136)

CRainSplashGenerator: Amend lower bound constant for speed in SSplashLine::Update()

---

Runtime/World/CDamageInfo.hpp
Runtime/World/CKnockBackController.cpp
Runtime/World/CMorphBall.cpp
Runtime/World/CPatterned.cpp
Runtime/World/CPlayer.cpp
Runtime/World/CWallCrawlerSwarm.cpp

Allows eliminating potential runtime static constructors by allowing file-scope instances to be declared constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/137)

CDamageInfo: Make certain constructors constexpr

---

Runtime/World/CScriptSound.cpp

Game code doesn't check for active status within this branch, and there's no comment indicating whether or not this difference was intentional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/138)

CScriptSound: Remove active check within AcceptScriptMsg() deactivate path

---

Runtime/World/IGameArea.hpp

In all usage cases, this variable is used with functions that expect a signed value. This eliminates quite a few signed mismatch warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/139)

IGameArea: Make Dock's reference count variable signed

---

Runtime/World/CScriptDock.hpp

Makes the enum type strongly typed. All usages currently allow for this anyways.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/140)

CScriptDock: Make EDockState an enum class

---

Runtime/World/CScriptActor.cpp
Runtime/World/CScriptCoverPoint.cpp
Runtime/World/CScriptDamageableTrigger.cpp
Runtime/World/CScriptDebris.cpp
Runtime/World/CScriptDock.cpp
Runtime/World/CScriptDoor.cpp
Runtime/World/CScriptGunTurret.cpp
Runtime/World/CScriptSpiderBallAttractionSurface.cpp
Runtime/World/CScriptTrigger.cpp
Runtime/World/CScriptVisorGoo.cpp

In some implementations, returning via default construction for std::optional can cause the entire inner buffer to be zeroed out. Returning with std::nullopt causes only the internal validity flag to be set and nothing more.
Given it's such a small change, there's no harm in doing this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/141)

CScript*: Return std::nullopt in GetTouchBounds()

---

Runtime/World/CScriptPlatform.cpp

Game code makes use of 1.66666675f here, not 0.0f.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/142)

CScriptPlatform: Amend delta time value in AcceptScriptMsg for deletion

---

Runtime/MP1/World/CWarWasp.cpp

GM8E v0-00 uses `2.5` for the second Arrival() damping radius value, not `3.0`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/143)

CWarWasp: Amend damping radius value within ApplyNormalSteering()

---

Runtime/MP1/World/CBloodFlower.cpp

Allows the strings to be put into the read-only section of the binary (and makes it explicit that the strings aren't modified). While we're at it we can make use of std::array.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/144)

CBloodFlower: Mark sFireEffects as constexpr

---

Runtime/MP1/World/CBloodFlower.cpp
Runtime/MP1/World/CBloodFlower.hpp

CBloodFlower seems to be missing the implementation of `GetCollisionResponseType()` from v0-00. This change adds in its equivalent behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/145)

CBloodFlower: Implement GetCollisionResponseType

---

Runtime/MP1/World/CFlickerBat.cpp

v0-00 contains a call to `SetMuted(false)` in game code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/146)

CFlickerBat: Add missing SetMuted() call within Death()

---

Runtime/MP1/World/CPuddleToadGamma.cpp
Runtime/MP1/World/CPuddleToadGamma.hpp

Makes the data fully internally-linked. This also allows declaring skBellyOffset as constexpr.
While we're at it, we can also make the solid filter constexpr as well, given it isn't modified anywhere. This allows the data to be placed within the read-only segment and potentially gets rid of a runtime static constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/147)

CPuddleToadGamma: Migrate static constants into the cpp file

---

Runtime/MP1/World/CFireFlea.cpp
Runtime/MP1/World/CFireFlea.hpp
Runtime/World/CPathFindSearch.hpp

v0-00 sets the padding member of CPathFindSearch here to `50.0`, not a member variable that's part of the CFireFlea class. With this, we can also remove the now-unused `xe64_` member within CFireFlea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/148)

CFireFlea: Set CPathFindSearch's padding to 50.0f within AcceptScriptMsg()

---

Runtime/MP1/World/CMetaree.cpp

v0-00 sets this locomotion type when the deactivation flag is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/149)

CMetaree: Set locomotion type to crouched if deactivated in InActive()

---

Runtime/MP1/World/CParasite.cpp

Same behavior, but allows the data to be stored within the read-only segment, and potentially gets rid of avoidable runtime constructors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/150)

CParasite: Make static CMaterialList instances constexpr where applicable

---

Runtime/Graphics/CGraphics.cpp

Makes the initializer field for the aspect member explicit along with the rest of the supplied values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/155)

CGraphics: Silence missing initializer warning

---

Runtime/Graphics/CSkinnedModel.cpp

Fairly straightforward change. We can move the elements here to make use of the move constructor over the copy constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/156)

CSkinnedModel: std::move constructor arguments where applicable

---

Runtime/World/CScriptVisorGoo.cpp

Same behavior, but without a verbose type name.
On some implementations, this also avoids zeroing out the buffer in the false case of the ternaries, but this isn't the main purpose of the PR. This is mainly a readability change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/157)

CScriptVisorGoo: Use std::make_optional where applicable

---

DataSpec/DNACommon/Tweaks/ITweakPlayerRes.hpp

Previously, all of these icons were using the first top icon, rather than their own respective icons.
While we're at it, we can also trim down some unnecessary `data()` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/160)

ITweakPlayerRes: Fix mismatched icon retrievals within ResolveResources()

---

Runtime/World/CPlayer.cpp

Previously, any call to this function would always reset the timer to 0.0, rather than potentially decrement it.
GM8E v0 always returns within the conditional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/161)

CPlayer: Add missing return within UpdateOrbitModeTimer()

---

Runtime/Weapon/CAuxWeapon.cpp

Given we already check if chargeState is Normal previously, there's no way that this can also be Charged at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/162)

CAuxWeapon: Replace always false condition with false in Fire()

---

DataSpec/DNACommon/Tweaks/ITweakGunRes.hpp
Runtime/Weapon/CGunWeapon.cpp
Runtime/Weapon/CPlayerGun.cpp

Makes use of std::array to deduplicate hardcoded array sizes and removes some unnecessary `c_str()` calls, which also eliminates unnecessary strlen calls, since string_view instances aren't being constructed around a regular C string anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/163)

ITweakGunRes: Minor cleanup

---

Runtime/Audio/CMidiManager.hpp

Provides the same behavior but without a redundant reference count increment and then decrement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/164)

CMidiManager: std::move sequencer within SetAudioSysHandle()

---

Runtime/Character/CGroundMovement.cpp

In GM8E v0, the wall elastic constant of the copied `SMovementOptions` instance is set to `0.03f`. This must have just been overlooked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/165)

CGroundMovement: Set optsCopy's wall elastic constant to 0.03f

---

Runtime/Character/CGroundMovement.cpp

The conditional itself aside, in GM8E v0, this is always assigned as `0.2f`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/166)

CGroundMovement: Collapse 'dampUnderwater ? 0.2f : 0.2f' conditional

---

DataSpec/SpecBase.cpp

We can use `insert()` with `std::make_move_iterator()` to perform the same behavior, minus unnecessary copies.
While we're at it, we can collapse the code within the Area case, since it's the exact same as the Mesh code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/167)

SpecBase: Flatten loop within flattenDependenciesBlend()

---

DataSpec/SpecBase.cpp

std::thread can already execute the supplied function as is without the assistance of std::bind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/168)

SpecBase: Remove redundant std::bind

---

DataSpec/DNACommon/Tweaks/ITweakPlayerRes.hpp

Performs the same changes that were recently applied to ITweakGunRes for consistency. Also eliminates some sign conversion warnings and deduplicates some array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/169)

ITweakPlayerRes: Make use of std::array where applicable

---

Runtime/Character/CPASAnimState.cpp
Runtime/Character/CPASAnimState.hpp
Runtime/Character/CPASDatabase.hpp
Runtime/Character/CPASParmInfo.hpp

Tidies up some `const_cast` usage, makes constructors explicit and makes some data members private that don't need to be public.
Each change should be fairly self contained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/171)

CPAS*: Minor cleanup

---

Runtime/Audio/CStreamAudioManager.cpp
Runtime/GuiSys/CHudBallInterface.cpp
Runtime/MP1/CFrontEndUI.cpp
Runtime/MP1/CFrontEndUI.hpp
Runtime/MP1/MP1.cpp
Runtime/World/CMorphBall.cpp

Makes for less noisy code and also gets rid of unnecessary `std::strlen` calls in the case the resulting pointer is passed to a `std::string_view` parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/173)

Runtime: Remove unnecessary c_str() calls

---

Runtime/Weapon/CBurstFire.cpp
Runtime/Weapon/CBurstFire.hpp
Runtime/World/CScriptGunTurret.cpp
Runtime/World/CScriptGunTurret.hpp

Makes the data fully internally linked and also allows making said data constexpr. This makes a minimal const adjustment to `CBurstFire`, to allow table data supplied to it to be constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/177)

CScriptGunTurret: Move static const data into the cpp file

---

Runtime/World/CScriptGunTurret.cpp

We can use `append()` instead of `data()`. This allows the size of the string view instance to be used directly instead of redundantly doing a string size lookup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/178)

CScriptGunTurret: Remove unnecessary data() call in AcceptScriptMsg()

---

Runtime/Weapon/CFlameThrower.cpp
Runtime/Weapon/CFlameThrower.hpp

GM8E v0 overrides `Render()`, `GetTouchBounds()` and `Touch()` and does nothing within them. This updates the interface to match it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/180)

CFlameThrower: Amend virtual interface discrepancies

---

Runtime/MP1/CInGameGuiManager.cpp

Trivially avoids an atomic reference count increment and decrement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/181)

CInGameGuiManager: Take std::shared_ptr by const reference in DoStateTransition()

---

Runtime/MP1/World/CThardus.cpp
Runtime/MP1/World/CThardus.hpp
Runtime/World/ScriptLoader.cpp

Previously the std::move calls wouldn't do anything, as the parameters were constant references, so we can take them by value and move into the constructor and then move the parameters into the member variables.
While we're at it, we can initialize the vectors in place instead of constructing and then assigning to them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/183)

CThardus: std::move vector instances in constructor

---

Runtime/Character/CParticleDatabase.cpp
Runtime/Character/CParticleGenInfo.hpp

Previously the particle system shared pointer would always be returned by value, rather than by reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/185)

CParticleGenInfo: Fix missing ampersand in GetParticleSystem() member function

---

Runtime/MP1/World/CThardus.cpp
Runtime/MP1/World/CThardus.hpp

Makes use of `std::make_unique` where applicable, and also gets rid of two implicit sign-conversion warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/187)

CThardus: Minor tidying changes

---

Runtime/Graphics/CModelBoo.cpp
Runtime/Graphics/Shaders/CModelShaders.hpp

Prevents pollution of the urde namespace with general names like `Flat`, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/188)

CModelShaders: Make EExtendedShader an enum class

---

Runtime/Graphics/CBooRenderer.cpp
Runtime/Graphics/CBooRenderer.hpp

Migrates the Bucket definition into the cpp file, making it feasible to change the implementation details without needing to rebuild everything that includes the header. While we're in the area, we can also make use of std::array to make array types more strongly typed and also eliminate some hardcoded array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/190)

CBooRenderer: Minor cleanup

---

Runtime/MP1/World/CEyeball.cpp

We can just fold the result into the constant directly, which allows us to avoid the need for a static runtime initializer. This is bit-exact with what the result would be, so this is fine.
While we're in the same area, we can also eliminate an unnecessary `.get()` call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/192)

CEyeball: Eliminate unnecessary runtime initializer in Think() 

---

Runtime/CToken.hpp

Prevents potential error-prone conversions from occurring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/193)

CToken: Make operator bool explicit

---

Runtime/Weapon/CProjectileInfo.cpp

GM8E v0 sets this to false before performing any further calculations. This also prevents accidental uninitialized usages from occurring if this is ever changed in the future. This also makes it nicer for debugging, since the variable will have a consistent value and not potentially contain junk between initial breakpoints.
While we're in the same area we can make bracing consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/194)

CProjectileInfo: Initialize result variable to false within PredictInterceptPos

---

Runtime/World/CPlayer.cpp

GM8E v0 makes use of the temporary collidable AA box. This amends the code to make use of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/195)

CPlayer: Make use of unused CCollidableAABox in ProcessInput()

---

Runtime/GuiSys/CSaveableState.hpp

Initializes the vectors in place, rather than constructing them and then resizing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/196)

CSaveableState: Initialize vectors in the constructor initializer list

---

Runtime/GuiSys/CFontRenderState.cpp

Unless I'm mistaken, this is identical behaviorally with what the game binary does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/197)

CFontRenderState: Collapse common switch cases in RefreshColor()

---

Runtime/CResFactory.cpp

The behavior on the right hand side would occur before the actual assignment, making the tag value invalidated. Instead, we copy the tag before the move is performed to keep the data valid when inserting it into the map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/198)

CResFactory: Resolve use-after-move in AddToLoadList()

---

Runtime/Graphics/CPVSVisOctree.cpp
Runtime/Graphics/CPVSVisOctree.hpp

It looks very odd using the name of the object being initialized to call through to a static member function. We can disambiguate this by making use of the qualifying name directly.
While we're in the same area we can do a little bit of tidying up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/199)

CPVSVisOctree: Use static qualifying name for ReadBoundingBoxBig()

---

Runtime/CToken.hpp
Runtime/Character/CAnimSourceReader.cpp
Runtime/Character/CFBStreamedCompression.hpp
Runtime/Character/CModelData.hpp

Has the same semantics of operator bool(), but explains at the call site what is actually being tested for in the relation to the object itself.
Aims to make readability slightly better (and removed the need for casts).
I'm open to better naming suggestions as well if this doesn't seem like an adequate name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/201)

CToken: Add HasReference() member function

---

Runtime/Character/CModelData.hpp

Prevents potentially error-prone conversions to bool. Similar to the changes recently made to CToken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/202)

CStaticRes: Make operator bool explicit

---

Runtime/Camera/CBallCamera.cpp

Same behavior, but less code.
This is identical in behavior to the code within the GM8E v0 binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/203)

CBallCamera: Collapse identical switch cases within AvoidGeometry()

---

Runtime/Character/CAnimData.cpp
Runtime/Character/CAnimData.hpp
Runtime/Character/CAnimSourceReader.cpp
Runtime/Character/CAnimSourceReader.hpp
Runtime/Character/CAnimSysContext.hpp
Runtime/Character/CAnimTreeAnimReaderContainer.cpp
Runtime/Character/CAnimTreeLoopIn.cpp
Runtime/Character/CAnimTreeLoopIn.hpp
Runtime/Character/CAnimTreeSequence.cpp
Runtime/Character/CAnimTreeSequence.hpp
Runtime/Character/CAnimationManager.hpp
Runtime/Character/CCharacterFactory.cpp
Runtime/Character/CFBStreamedAnimReader.hpp
Runtime/Character/CSequenceHelper.cpp
Runtime/Character/CSequenceHelper.hpp
Runtime/Character/CTransitionDatabaseGame.cpp
Runtime/Character/CTransitionDatabaseGame.hpp
Runtime/Character/CTransitionManager.hpp

Makes the interfaces more flexible by allowing parameters to be moved into if permissible in calling code. This prevents unnecessary copies in some cases and also prevents some avoidable atomic reference count increments and decrements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/204)

Character/*: std::move constructor parameters where applicable

---

Runtime/CFactoryMgr.cpp
Runtime/CFactoryMgr.hpp

- `std::move`s `std::function` arguments to `AddFactory()` and also gets rid of unnecessary default construction
- Makes use of `std::array` where applicable
- Resolves a variable shadowing warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/205)

CFactoryMgr: Minor cleanup

---

Runtime/Graphics/Shaders/CElementGenShaders.cpp
Runtime/Particle/CElementGen.cpp
Runtime/Particle/CElementGen.hpp

- Makes the use of `std::array` more consistent.
- Resolves avoidable implicit sign-conversion warnings
- Makes `GetSystemCount()` a const member function
- `std::move`s the TToken instance in the constructor to allow calling code to move into it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/206)

CElementGen: Minor cleanup

---

Runtime/Weapon/CElectricBeamProjectile.cpp

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/207)

CElectricBeamProjectile: Remove unnecessary get() calls in PreRender()

---

Runtime/Weapon/CWaveBuster.cpp
Runtime/Weapon/CWaveBuster.hpp

Implements GetTouchBounds() according to the implementation within the GM8E v0 binary.
Fills out the implementation of CWaveBuster a little bit, getting rid of some low-hanging fruit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/208)

CWaveBuster: Implement GetTouchBounds()

---

Runtime/Weapon/CPlayerGun.cpp
Runtime/World/CPlayer.cpp
Runtime/World/CPlayerCameraBob.cpp
Runtime/World/CPlayerCameraBob.hpp

- Makes use of `std::array` where applicable
- Makes static data members private. Many of them aren't even used outside of the class. Prevents accidental modification of the values across refactors, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/210)

CPlayerCameraBob: Minor cleanup

---

Runtime/World/CPlayer.hpp
Runtime/World/CPlayerEnergyDrain.cpp
Runtime/World/CPlayerEnergyDrain.hpp

GM8E v0 initializes this to zero when constructing the class. This also makes the entire class have a consistent initial state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/211)

CPlayerEnergyDrain: Initialize x10_energyDrainTime on construction

---

Runtime/Weapon/CPowerBomb.cpp
Runtime/Weapon/CPowerBomb.hpp

Hides the name from external view entirely and allows the color instance to be constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/212)

CPowerBomb: Make kFadeColor internally linked

---

Runtime/Weapon/CGunWeapon.cpp
Runtime/Weapon/CGunWeapon.hpp

This class is used as polymorphic type, so the destructor should be marked as virtual to prevent any potential undefined behavior.
This also more closely matches the GM8E v0 binary itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/214)

CGunWeapon: Make destructor virtual

---

Runtime/MP1/CFrontEndUI.hpp

This is the initial value that GM8E v0 assigns to this member variable. Previously it was being left uninitialized on construction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/215)

CFrontEndUI: Default initialize SFrontEndFrame's x4_action to EAction::None

---

Runtime/Graphics/CLineRenderer.cpp

We can just initialize maxTriVerts to zero to prevent warnings from occurring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/216)

CLineRenderer: Silence -Wmaybe-uninitialized warning

---

Runtime/Camera/CPathCamera.cpp

Same thing, but without implicit conversion to bool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/219)

CPathCamera: Change 0 to false in CPathCamera constructor

---

Runtime/GuiSys/CFontImageDef.cpp

Same behavior, but constructs the instances directly within the container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/221)

CFontImageDef: Make use of emplace_back where applicable

---

Runtime/CGameHintInfo.cpp
Runtime/CGameHintInfo.hpp
Runtime/CGameOptions.cpp
Runtime/CGameOptions.hpp
Runtime/World/CScriptSpecialFunction.cpp

Enforces the use of valid strings in the interface. Also reduces `c_str()` noise a little bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/222)

CGameOptions: Make use of std::string_view where applicable

---

Runtime/CMemoryCardSys.hpp

Prevents implicit error-prone conversions to bool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/224)

CMemoryCardSys: Make CardResult's conversion operator explicit

---

Runtime/CArchitectureQueue.hpp

Prevents potentially error-prone implicit conversion contexts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/225)

CArchitectureQueue: Make operator bool explicit

---

Runtime/Character/CAnimSource.cpp

We can make use of std::clamp instead of std::min and std::max
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/226)

CAnimSource: Simplify ClampZeroToOne()

---

Runtime/Character/CCharAnimTime.cpp
Runtime/Character/CCharAnimTime.hpp

These can be made constexpr to allow use at compile-time, given these only hold an enum and a floating point value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/228)

CCharAnimTime: Make constructors constexpr where applicable

---

Runtime/GuiSys/CHudEnergyInterface.cpp
Runtime/GuiSys/CHudMissileInterface.cpp
Runtime/GuiSys/CHudThreatInterface.cpp
Runtime/GuiSys/CHudVisorBeamMenu.cpp

Same behavior, but more strongly typed. While we're at it, we can mark them all as constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/220)

CHud*: Make use of std::array where applicable

---

Runtime/Collision/CCollisionActor.cpp

While we're at it, change the g to s, since it's internally linked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/229)

CCollisionActor: Mark gkDefaultCollisionActorMaterials as constexpr

---

Runtime/MP1/CPauseScreenBlur.cpp
Runtime/MP1/CPauseScreenBlur.hpp

Draw() clearly modifies the internals of the class in a non-caching manner, so this member function should really not have a const qualifier on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/231)

CPauseScreenBlur: Remove const_cast in Draw()

---

Runtime/Graphics/Shaders/CPhazonSuitFilter.cpp

Same behavior, but with a more localized scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/232)

CPhazonSuitFilter: Convert define into local variable

---

Runtime/MP1/World/CPuffer.cpp

Allows direct size querying, which allows removing the use of direct hardcoded array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/235)

CPuffer: Make use of std::array where applicable

---

Runtime/MP1/World/CPuddleSpore.cpp
Runtime/MP1/World/CPuddleSpore.hpp

Makes the data an implementation detail and also allows for the string_view array to be declared constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/234)

CPuddleSpore: Make static const class data internally linked

---

Runtime/CStateManager.cpp
Runtime/CStateManager.hpp

Trims down the usage of `const_cast` where applicable among other things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/237)

CStateManager: Casting-related cleanups

---

Runtime/Graphics/Shaders/CFogVolumeFilter.cpp

Makes data strongly typed and also allows for the removal of some
hardcoded array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/238)

CFogVolumeFilter: Make use of std::array where applicable

---

Runtime/Graphics/CLineRenderer.cpp
Runtime/Graphics/CLineRenderer.hpp
Runtime/Graphics/Shaders/CLineRendererShaders.cpp

- Remove unnecessary casts to bool
- Make use of std::array where applicable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/239)

CLineRenderer: Minor changes

---

Runtime/MP1/CMainFlow.cpp

Same behavior, but without a redundant atomic reference count increment/decrement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/240)

CMainFlow: std::move shared_ptr in SetGameState

---

Runtime/Graphics/CLight.cpp
Runtime/Graphics/CLight.hpp

- Remove unnecessary initializer list initializers 
- Prevent implicit double->float truncations
- Mark kDefaultPosition and kDefaultDirection as constexpr
- Mark caching member variables as mutable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/243)

CLight: Minor cleanup

---

Runtime/GuiSys/CAuiEnergyBarT01.cpp
Runtime/GuiSys/CAuiEnergyBarT01.hpp
Runtime/GuiSys/CAuiImagePane.cpp
Runtime/GuiSys/CAuiImagePane.hpp

Same behavior but allows dehardcoding array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/244)

CAui*: Make use of std::array where applicable

---

Runtime/GuiSys/CDrawStringOptions.hpp

Same behavior, but constructs the vector with the necessary size, rather than constructing and resizing after the fact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/245)

CDrawStringOptions: Resize vector within constructor

---

Runtime/Collision/CCollisionInfoList.hpp

Same behavior, but without a verbose return type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/246)

CCollisionInfoList: Simplify definition of begin() and end()

---

Runtime/Weapon/CFlameThrower.cpp

Resolves trivial sign conversion warnings and also makes some variables const where applicable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/247)

CFlameThrower: Resolve sign-conversion warnings in DoCollisionCheck()

---

Runtime/CStateManager.cpp
Runtime/CStateManager.hpp

Same behavior, but allows dehardcoding array sizes and makes the array types more strongly typed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/250)

CStateManager: Make use of std::array where applicable

---

Runtime/Input/CRumbleVoice.cpp

Same behavior, but constructs in place with the size, rather than constructing and then resizing.
`x20_handleIds` cannot be done the same way unfortunately, as `reserved_vector` doesn't have a constructor accepting a size argument like `std::vector` does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/252)

CRumbleVoice: Resize vectors within constructor initializer list

---

Runtime/CRelayTracker.cpp
Runtime/CRelayTracker.hpp

While we're at it, we can make use of HasRelay() internally where applicable to simplify code a little bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/253)

CRelayTracker: Make HasRelay() a const member function

---

Runtime/MP1/World/CActorContraption.cpp

Same behavior, but with better names than `first` or `second`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/256)

CActorContraption: Make use of structured bindings where applicable

---

Runtime/AutoMapper/CAutoMapper.cpp
Runtime/CStateManager.cpp
Runtime/World/CWorld.cpp
Runtime/World/CWorld.hpp

Allows const overloading to function properly and prevents potential compilation errors from occurring if constness on functions is ever changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/257)

CWorld: Rename IMapWorld to IGetMapWorld()

---

Runtime/CPlayerState.cpp
Runtime/CPlayerState.hpp

We can default the CPowerUp constructor to make the default constructor trivial. While we're in the area, we can remove type-punning via unions, which is undefined behavior in C++.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/259)

CPlayerState: Default CPowerUp constructor and also remove undefined behavior

---

Runtime/CPlayerState.cpp
Runtime/CPlayerState.hpp

While useful as a map, this causes an allocation that occurs during program start and lasts until the program terminates, even if the relevant code is never executed.
Given the total number of elements is quite small, we can convert this into a compile-time array and perform the lookup with that instead. While we're at it, we can eliminate an unnecessary second lookup into said array by reusing the iterator from the first find.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/260)

CPlayerState: Make g_typeNameMap a compile-time array

---

Runtime/Weapon/CBomb.cpp

Allows the data to be placed into the read-only segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/261)

CBomb: Make file-scope material filter constexpr

---

Runtime/Weapon/CBeamProjectile.cpp

Allows some implementations to completely avoid zeroing out the internal buffer within the std::optional instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/262)

CBeamProjectile: Explicitly return std::nullopt in GetTouchBounds()

---

Runtime/Particle/CDecal.cpp
Runtime/Particle/CDecal.hpp

Same behavior, but with stronger-typing and no implicit array to pointer decay.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/263)

CDecal: Make use of std::array where applicable

---

Runtime/Particle/CModVectorElement.hpp
Runtime/Particle/CParticleDataFactory.cpp

There's no real need to std::move a primitive type. A copy will be performed either way. We can remove std::move in this case to improve readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/264)

General: Remove unnecessary std::move calls

---

Runtime/RetroTypes.hpp

- Mark return types as `[[nodiscard]]` where applicable, given these types have a large project-wide surface area.
- Take types in comparisons by value where applicable. All of these types are very small, so we can just take them by value to get rid of unnecessary memory referencing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/265)

RetroTypes: Minor adjustments

---

Runtime/Particle/CParticleElectric.cpp

Makes it obvious that std::unique_ptr instances are being created within the implementation code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/266)

CParticleElectric: Use std::make_unique where applicable

---

Runtime/Character/CAnimData.hpp

Provides at least some form of name for all functions in the interface. This allows IDEs to perform proper name inspection (as well as being slightly more informative to the reader in some cases).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/267)

CAnimData: Give names to function prototype parameters

---

Runtime/Particle/CIntElement.cpp
Runtime/Particle/CIntElement.hpp

CIESampleAndHold caches values internally for use later in a non-visible manner to the user of the class. This is a good place for mutable to be used.
This improves the readability of the GetValue() implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/268)

CIntElement: Remove const_cast

---

Runtime/World/CPlayer.cpp

Makes the code much more sequentially readable by placing the guard clauses first before the performed behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/270)

CPlayer: Un-nest code within FinishNewScan()

---

Runtime/World/CFluidPlane.cpp

Avoids a -Wmaybe-uninitialized warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/272)

CFluidPlane: Always initialize mul to 0.0f in CalculateRippleIntensity()

---

Runtime/World/CTeamAiMgr.hpp

Makes all class members have a deterministic initial state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/273)

CTeamAiMgr: Initialize x90_timeSinceMelee and x90_timeSinceRanged to 0.0f in constructor

---

Runtime/CGameState.cpp

Unless I'm mistaken, GM8E v0 stores the HP value of the loaded player state into the returned
GameFileStateInfo instance.
This prevents the health value from being returned uninitialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/274)

CGameState: Set HP value in LoadGameFileState()

---

Runtime/CPlayerState.cpp
Runtime/CPlayerState.hpp
Runtime/World/CPlayer.cpp

Allows const overloading to function and prevents compilation errors from occurring if constness changes through future changes of any sort.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/275)

CPlayerState: Rename HealthInfo() to GetHealthInfo()

---

Runtime/Collision/CCollisionActor.cpp
Runtime/Collision/CCollisionActor.hpp

Makes the interface more self-documenting at a glance and allows IDEs to do better parameter inspection at call sites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/276)

CCollisionActor: Provide parameter names in interface where applicable

---

Runtime/Graphics/CBooRenderer.cpp
Runtime/Graphics/CModel.hpp
Runtime/Graphics/CModelBoo.cpp
Runtime/GuiSys/CAuiEnergyBarT01.cpp
Runtime/GuiSys/CAuiEnergyBarT01.hpp
Runtime/GuiSys/CAuiImagePane.cpp
Runtime/GuiSys/CAuiImagePane.hpp
Runtime/GuiSys/CGuiCamera.cpp
Runtime/GuiSys/CGuiCamera.hpp
Runtime/GuiSys/CGuiFrame.cpp
Runtime/GuiSys/CGuiFrame.hpp
Runtime/GuiSys/CGuiModel.cpp
Runtime/GuiSys/CGuiModel.hpp
Runtime/GuiSys/CGuiObject.cpp
Runtime/GuiSys/CGuiObject.hpp
Runtime/GuiSys/CGuiTextPane.cpp
Runtime/GuiSys/CGuiTextPane.hpp
Runtime/GuiSys/CGuiWidget.cpp
Runtime/GuiSys/CGuiWidget.hpp
Runtime/World/CMorphBallShadow.cpp

Many functions are modifying internals of CBooModel and const-casting is performed in order to work around functions being const when they really shouldn't be.
This amends the function signatures in order to allow these functions to exist without const_cast, making code much nicer to read.
Preferably it'd be nice if this one was run through CI before merging, to make sure I didn't miss anything that might have been platform-specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/255)

CModelBoo: Remove usages of const_cast

---

Runtime/World/CScannableParameters.hpp

This only contains a single member, so this can trivially be marked constexpr.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/279)

CScannableParameters: Mark CScannableParameters as constexpr

---

Runtime/CToken.cpp
Runtime/CToken.hpp

Allows containers and anything using std::move_if_noexcept to perform a move instead of a copy internally if reallocations are necessary.
`TToken` should likely also have a move assignment operator instead of only a copy assignment constructor, as this means all attempted `TToken`, `TCachedToken` and `TLockedToken` moves will fallback to the copy assignment operator in certain circumstances, which is a little suboptimal. However I think someone that has more intimate knowledge of the token classes should implement this.
`TLockedToken` similarly only has copy constructor/assignment defined for it, but not move construction/assignment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

CToken: Mark move assignment operator as noexcept

---

Runtime/GuiSys/CTextRenderBuffer.cpp
Runtime/GuiSys/CTextRenderBuffer.hpp

These are only used internally, so we can completely hide these structs
from external view. This allows their implementation to be changed without needing to recompile all the headers that include it.

CTextRenderBuffer: Forward declare structs where applicable

---

Runtime/CIOWin.hpp
Runtime/CPlayMovieBase.hpp
Runtime/GuiSys/CConsoleOutputWindow.cpp
Runtime/GuiSys/CConsoleOutputWindow.hpp
Runtime/GuiSys/CErrorOutputWindow.cpp
Runtime/GuiSys/CErrorOutputWindow.hpp
Runtime/GuiSys/CSplashScreen.cpp
Runtime/GuiSys/CSplashScreen.hpp
Runtime/MP1/CCredits.cpp
Runtime/MP1/CCredits.hpp
Runtime/MP1/CFrontEndUI.cpp
Runtime/MP1/CFrontEndUI.hpp
Runtime/MP1/CMFGame.cpp
Runtime/MP1/CMFGame.hpp
Runtime/MP1/CMainFlow.hpp
Runtime/MP1/CSlideShow.cpp
Runtime/MP1/CSlideShow.hpp

Allows removing several const_cast usages within the codebase.

CIOWin: Make Draw() non-const

---

Runtime/Character/CAnimTreeAnimReaderContainer.cpp

It seems quite suspect to read all integral values as bools.

CAnimTreeAnimReaderContainer: Correct call to VGetBoolPOIState() within VGetInt32POIState()

---

Runtime/Character/CAnimTreeDoubleChild.cpp

Like the previous change, it's awfully suspect to be interpreting all integer values as bools.

CAnimTreeDoubleChild: Correct call to VGetBoolPOIState() in VGetInt32POIState()

---

Runtime/Character/CAnimSourceReader.cpp
Runtime/Character/CAnimSourceReader.hpp
Runtime/Character/CAnimTreeAnimReaderContainer.cpp
Runtime/Character/CAnimTreeAnimReaderContainer.hpp
Runtime/Character/CAnimTreeDoubleChild.cpp
Runtime/Character/CAnimTreeDoubleChild.hpp
Runtime/Character/CAnimTreeSingleChild.cpp
Runtime/Character/CAnimTreeSingleChild.hpp
Runtime/Character/CAnimTreeTimeScale.cpp
Runtime/Character/CAnimTreeTimeScale.hpp
Runtime/Character/IAnimReader.hpp

Same behavior, but allows interoperating with different string types in a more straightforward manner.

IAnimReader: Make use of std::string_view where applicable

---

Runtime/AutoMapper/CAutoMapper.cpp
Runtime/AutoMapper/CAutoMapper.hpp
Runtime/AutoMapper/CMapArea.cpp
Runtime/AutoMapper/CMapArea.hpp
Runtime/AutoMapper/CMapUniverse.cpp
Runtime/AutoMapper/CMapUniverse.hpp
Runtime/AutoMapper/CMapWorld.cpp
Runtime/AutoMapper/CMapWorld.hpp
Runtime/AutoMapper/CMappableObject.cpp
Runtime/AutoMapper/CMappableObject.hpp
Runtime/MP1/CInGameGuiManager.cpp
Runtime/MP1/CInGameGuiManager.hpp
Runtime/World/CScriptDoor.cpp
Runtime/World/CWorld.hpp

Same behavior, but makes it explicit from the interface that modifications are clearly going on from within the class.

CAutoMapper: Eliminate usages of const_cast

---

Runtime/Character/CAdditiveAnimPlayback.cpp
Runtime/Character/CAnimSource.cpp
Runtime/Character/CSegStatementSet.hpp

- Make x4_segData private. We already have accessors for retrieving the data, so we can use those instead.
- Make use of std::array. Same behavior, but without any implicit array to pointer decay.

CSegStatementSet: Minor changes

---

Runtime/GuiSys/CRasterFont.cpp
Runtime/GuiSys/CRasterFont.hpp

CRasterFont: Collapse loop into a std::find_if in InternalGetGlyph()

---

CMakeLists.txt

Makes MSVC more standards compliant regarding various C++ constructs.

CMakeLists: Enable several conformance flags on MSVC

---

Runtime/Camera/CCameraShakeData.cpp
Runtime/Camera/CCameraShakeData.hpp
Runtime/Weapon/CAuxWeapon.cpp
Runtime/Weapon/CPlasmaBeam.cpp

Same behavior, but allows eliminating file-scope initializers needing to be run on program start.
Opening this as a PR to run CI over it.

CCameraShakeData: Make classes and structs constexpr where applicable

---

Runtime/Camera/CCameraFilter.cpp
Runtime/Camera/CCameraFilter.hpp

Eliminates another usage of const_cast.

CCameraFilter: Make Draw() non-const

---

Runtime/Character/CAnimData.hpp
Runtime/Weapon/CGunWeapon.cpp
Runtime/Weapon/CGunWeapon.hpp
Runtime/Weapon/CPhazonBeam.cpp
Runtime/Weapon/CPhazonBeam.hpp
Runtime/Weapon/CPlayerGun.cpp
Runtime/Weapon/CPlayerGun.hpp

Eliminates trivial usages of const_cast by making Draw related functions non-const. This also allows removing the mutable specifiers from several shader data members.

CGunWeapon: Eliminate usages of const_cast

---

CMakeLists.txt

Makes use of the latest standards on MSVC, allowing potential compilation issues to be diagnosed as soon as possible

CMakeLists: Specify /std:c++latest on MSVC

---

Runtime/Character/CAnimData.cpp
Runtime/Character/CAnimSourceReader.cpp
Runtime/Character/CAnimSourceReader.hpp
Runtime/Character/CAnimTreeAnimReaderContainer.cpp
Runtime/Character/CAnimTreeAnimReaderContainer.hpp
Runtime/Character/CAnimTreeDoubleChild.cpp
Runtime/Character/CAnimTreeDoubleChild.hpp
Runtime/Character/CAnimTreeLoopIn.cpp
Runtime/Character/CAnimTreeLoopIn.hpp
Runtime/Character/CAnimTreeSequence.cpp
Runtime/Character/CAnimTreeSequence.hpp
Runtime/Character/CAnimTreeSingleChild.cpp
Runtime/Character/CAnimTreeSingleChild.hpp
Runtime/Character/CAnimTreeTimeScale.cpp
Runtime/Character/CAnimTreeTimeScale.hpp
Runtime/Character/CPOINode.cpp
Runtime/Character/CPOINode.hpp
Runtime/Character/CSequenceHelper.cpp
Runtime/Character/IAnimReader.cpp
Runtime/Character/IAnimReader.hpp
Runtime/Character/IMetaAnim.cpp

Allows using container sizes and capacities without needing to cast them, allowing for dehardcoding of array sizes in some scenarios.

IAnimReader: Make use of size_t for capacity and iterators

---

Runtime/Graphics/CModel.hpp

Allows initializers to be elided where applicable. While we're at it, we can make the conditional flag tests more explicit and eliminate implicit truncation in the case of the second flag test.

CModel: Make CModelFlags constexpr.

---

Runtime/CRandom16.hpp
Runtime/Graphics/CRainSplashGenerator.hpp
Runtime/Weapon/CNewFlameThrower.hpp
Runtime/Weapon/CWaveBuster.hpp
Runtime/World/CMorphBall.hpp

Same behavior, minus the implicit conversions upon construction.

CRandom16: Make constructor explicit

---

Runtime/MP1/World/CBeetle.cpp
Runtime/Particle/CDecal.cpp
Runtime/Weapon/CGunMotion.cpp
Runtime/Weapon/CGunWeapon.cpp
Runtime/Weapon/CPlayerGun.cpp
Runtime/Weapon/CProjectileWeapon.cpp
Runtime/World/CFishCloud.cpp
Runtime/World/CMorphBall.cpp
Runtime/World/CPlayer.cpp
Runtime/World/CSnakeWeedSwarm.cpp
Runtime/World/CWallCrawlerSwarm.cpp

Allows more runtime initializes to potentially be elided.

CModel: Mark CModelFlag instances as constexpr where applicable

---

Runtime/World/CMorphBall.cpp

Same behavior, but allows elision of runtime initializers.
Opening this as its own PR to see if we properly handle `extern const` identifiers being defined with constexpr.

CMorphBall: Make use of constexpr on file-scope arrays

---

Runtime/World/CFluidPlane.cpp
Runtime/World/CFluidPlane.hpp
Runtime/World/CFluidPlaneCPU.cpp
Runtime/World/CFluidPlaneCPU.hpp
Runtime/World/CFluidPlaneDoor.cpp
Runtime/World/CFluidPlaneGPU.cpp
Runtime/World/CFluidPlaneGPU.hpp

Makes all the arrays strongly typed. We can also use type aliases to greatly shorten some type definitions and make them less verbose.

CFluidPlane: Make use of std::array where applicable

---

Runtime/CScannableObjectInfo.hpp
Runtime/GuiSys/CScanDisplay.cpp
Runtime/GuiSys/CScanDisplay.hpp
Runtime/MP1/CLogBookScreen.cpp
Runtime/MP1/CPauseScreenBase.cpp
Runtime/MP1/CPauseScreenBase.hpp

Removes implicit sign conversions and also dehardcodes quite a bit of repeated sizes.
Making this a PR so someone can give it a once-over.

CScanDisplay: Eliminate implicit sign conversions

---

Runtime/GuiSys/CGuiWidgetDrawParms.cpp
Runtime/GuiSys/CGuiWidgetDrawParms.hpp
Runtime/GuiSys/CHudDecoInterface.cpp
Runtime/GuiSys/CMakeLists.txt
Runtime/MP1/CFrontEndUI.cpp
Runtime/MP1/CSamusHud.cpp
Runtime/MP1/CSaveGameScreen.cpp

We can allow this structure to be constructed in a constexpr context.
This also allows us to remove the cpp file, given it's no longer necessary.

CGuiWidgetDrawParms: Make constexpr constructible

---

Runtime/CObjectList.hpp

Provides const overloads of begin() and end(), so that range for may be used within const contexts. While we're in the same area, we can make the constructor explicit and provide operator== for iterators in conjunction with operator!=.

CObjectList: Minor interface modifications

---

Runtime/rstl.hpp

We can make use of `std::make_reverse_iterator` to automatically create the reverse iterators. This allows eliminating some code specifically for handling the reverse iterators.

rstl: Remove need for manual reverse iterators

---

Runtime/rstl.hpp

Given we're iterating over a contiguous sequence with iterators like these, we can use the contiguous_iterator_tag introduced within C++20 to signify this.

rstl: Make iterator tag use std::contiguous_iterator_tag

---

Runtime/Audio/CSfxManager.cpp

Same behavior, less duplication of variable names.
Originally I'd push this to master, but want to double check that the appveyor buildbot will compile with it.

CSfxManager: Make use of designated initializers

---

Runtime/MP1/World/CMetroidPrimeRelay.cpp
Runtime/World/CScriptMazeNode.cpp

Xcode: v12.3
MacOS: Big Sur
On building, receive two errors of the same type:
This change allows the build to complete without errors.

Bugfix: Xcode build "loop variable <X> is always a copy " error fix

---

Runtime/MP1/World/CBouncyGrenade.cpp
Runtime/World/CScriptMazeNode.cpp

Recently applying constexpr to these lambdas has been producing an error on Windows 10
```
error: constexpr function never produces a constant expression [-Winvalid-constexpr]
```
I understand the intention is to find the root of the problem and fix it, however until then Windows (and possibly other platforms) are unable to compile without removing `constexpr`. Since this has no serious downside, I believe we should just remove them so that those having this error can compile.

[Windows] Remove constexpr from Lambda functions to fix compiler errors.

---

Editor/ViewManager.cpp
Runtime/Graphics/CGraphics.cpp
Runtime/Graphics/CGraphics.hpp

Implemented CGraphics::GetFPS() which returns the fps value that is updated at the end of each scene, and displays it if the [debugOverlayShowFramerate](https://github.com/AxioDL/hecl/pull/39) cvar is set. This FPS value is the amount of frames that have past at the end of every second, calculated using the Chrono library.
The FPS counter isn't coded exactly like the function found in MP1's binary, the primary differences are the FPS counter uses Chrono to gather time, doesn't write a "previous framerate" value (which I believe is unused in the game as well) and is capable of working with a variable framerate. Since Boo isn't written to be a replica of the game's graphics engine I doubt this will be an issue.

CGraphics: FPS Counter and debug overlay

---

Runtime/CDvdFile.cpp

Do nothing if either m_complete or m_cancel is set, avoiding waiting for the mutex for no reason.

Improve CFileDvdRequest::PostCancelRequest

---

Runtime/Graphics/CBooRenderer.cpp
Runtime/Graphics/CModel.hpp
Runtime/Graphics/CModelBoo.cpp

This shares the IGraphicsDataFactory::Context over many functions, to avoid
the overhead of calling CGraphics::CommitResources multiple times.

Combine CommitResources for CBooRenderer::UpdateAreaUniforms.

---

README.md

This should not break compatibility with older versions
qt5-default no longer exists as a package in apt repositories

fix dependencies for Ubuntu 21.04+/Debian 11+
