AxioDL/metaforce

- DataSpec/DNACommon/ANCS.hpp
- DataSpec/DNACommon/ANIM.cpp
- DataSpec/DNACommon/CMDL.hpp
- DataSpec/DNACommon/PAK.hpp
- DataSpec/DNAMP1/DNAMP1.cpp
- DataSpec/DNAMP1/DNAMP1.hpp
- DataSpec/DNAMP1/PAK.cpp
- DataSpec/DNAMP1/PAK.hpp
- DataSpec/DNAMP2/DNAMP2.cpp
- DataSpec/DNAMP2/DNAMP2.hpp
- DataSpec/DNAMP3/CMDLMaterials.cpp
- DataSpec/DNAMP3/DNAMP3.cpp
- DataSpec/DNAMP3/DNAMP3.hpp
- DataSpec/DNAMP3/PAK.cpp
- DataSpec/DNAMP3/PAK.hpp
- DataSpec/SpecBase.cpp
- DataSpec/SpecBase.hpp
- DataSpec/SpecMP1.cpp
- DataSpec/SpecMP2.cpp
- DataSpec/SpecMP3.cpp
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'><img src='http://www.codereviewhub.com/site/github-bar.png' height=40></a>
<a href='https://www.codereviewhub.com/AxioDL/PathShagged/pull/4?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/AxioDL/PathShagged/pull/4'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
<a href='#crh-end'></a>
> Initial cook tool integration

- Editor/GameMode.hpp
- Editor/InformationCenter.hpp
- Editor/ModelViewer.hpp
- Editor/ParticleEditor.hpp
- Editor/ProjectManager.hpp
- Editor/ResourceBrowser.hpp
- Editor/Space.hpp
- Editor/SplashScreen.hpp
- Editor/ViewManager.hpp
- Editor/main.cpp
Continues the override modernization with the Editor code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/34)
> Editor: Use override where applicable

- DataSpec/DNACommon/CMDL.cpp
- DataSpec/DNACommon/DNACommon.hpp
- DataSpec/DNAMP1/DCLN.hpp
- DataSpec/DNAMP1/SCAN.hpp
Marks member functions that don't modify instance state as const.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/43)
> RetroDataSpec: Make member functions const where applicable

- DataSpec/SpecBase.hpp
Complements https://github.com/AxioDL/hecl/pull/24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/51)
> SpecBase: Add missing includes

- DataSpec/DNACommon/CMDL.cpp
- DataSpec/DNACommon/PAK.hpp
- DataSpec/DNAMP1/DNAMP1.cpp
- DataSpec/DNAMP1/MREA.cpp
- DataSpec/DNAMP1/SCLY.cpp
- DataSpec/DNAMP2/DNAMP2.cpp
- DataSpec/DNAMP2/MREA.cpp
- DataSpec/DNAMP2/MREA.hpp
- DataSpec/DNAMP3/CHAR.cpp
- DataSpec/DNAMP3/DNAMP3.cpp
- DataSpec/DNAMP3/MREA.cpp
- DataSpec/DNAMP3/MREA.hpp
- DataSpec/DNAMP3/PAK.cpp
- DataSpec/DNAMP3/PAK.hpp
- DataSpec/DNAMP3/STRG.cpp
- DataSpec/SpecMP1.cpp
- Editor/ProjectManager.cpp
Allows this code to continue functioning when the enum is changed over to an enum class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/59)
> General: Be explicit about athena's SeekOrigin type

- DataSpec/DNAMP1/MREA.cpp
This was missed in 9c0d13f0011943908140ac33e5b1acc37828ce49
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/60)
> DataSpec: Be explicit about athena's SeekOrigin type

- Runtime/CCRC32.cpp
- Runtime/CCRC32.hpp
This can be moved entirely into the cpp file, making it an implementation detail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/62)
> CCRC32: Move table declaration into the cpp file

- DataSpec/DNACommon/DNACommon.hpp
- DataSpec/DNACommon/GX.cpp
- DataSpec/DNACommon/GX.hpp
- DataSpec/DNAMP1/AGSC.cpp
- DataSpec/DNAMP2/AGSC.cpp
- Editor/Space.hpp
Allows this code to still compile if the Endian type is ever changed into a strong enumeration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/67)
> General: Be explicit about athena's Endian type

- Runtime/CSortedLists.cpp
- Runtime/CSortedLists.hpp
Makes use of std::array where applicable, and turns ESortedList into an enum class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/71)
> CSortedLists: Minor changes

- Runtime/MP1/CSlideShow.cpp
Provides the same behavior, but without any magic size values
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/93)
> CSlideShow: Use ranged for loops in constructor

- Runtime/AutoMapper/CAutoMapper.cpp
- Runtime/AutoMapper/CAutoMapper.hpp
A few isolated minor changes to the automapper code. Mostly consists of stronger typing and warning fixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/97)
> CAutoMapper: Minor changes

- Runtime/MP1/World/CAtomicAlpha.cpp
- Runtime/MP1/World/CAtomicAlpha.hpp
- Runtime/MP1/World/CAtomicBeta.cpp
- Runtime/MP1/World/CAtomicBeta.hpp
Hides two arrays from external view completely, and also makes some minor code adjustment changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/98)
> CAtomicAlpha/CAtomicBeta: Minor changes

- Runtime/MP1/CArtifactDoll.cpp
Primarily makes use of std::array in order to dehardcode a few magic numbers related to sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/113)
> CArtifactDoll: Minor changes

- Runtime/Graphics/CModel.hpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/114)
> CModel: Implement CModelFlags' operator!= in terms of operator==

- Runtime/Character/CCharLayoutInfo.cpp
- Runtime/Character/CCharLayoutInfo.hpp
Notably, this allows heterogenous lookup within `GetSegIdFromString()`, making the function entirely non-allocating, since std::string_view can now be used seamlessly with find() calls. Other changes are mostly just cosmetic cleanups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/117)
> CCharLayoutInfo: Minor changes

- Runtime/IOStreams.cpp
Some minor changes that tidy up the interface a little bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/121)
> IOStreams: Minor changes

- visigen/VISIRenderer.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/122)
> visigen: Fix parent PID from argv

- Runtime/GuiSys/CGuiTextSupport.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/129)
> CGuiTextSupport: Make use of emplace_back() in AddText()

- Runtime/MP1/World/CAtomicBeta.cpp
This is supposed to be a multiplication, not a division (at least this is what v0-00 does).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/151)
> CAtomicBeta: Correct division arithmetic error in Think()

- DataSpec/SpecBase.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/152)
> Fixed character type mismatch.

- Runtime/MP1/CSamusDoll.cpp
- Runtime/MP1/CSamusDoll.hpp
A few minor changes that don't really deserve their own PRs. Notably, it eliminates a case of variable shadowing. Each change should be fairly self explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/154)
> CSamusDoll: Minor changes

- Runtime/MP1/World/CJellyZap.cpp
- Runtime/MP1/World/CJellyZap.hpp
This can be trivially made constexpr. We can also make this a fully internally linked identifier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/159)
> CJellyZap: Make kPlayerFilter constexpr

- Runtime/Collision/CollisionUtil.cpp
Same thing, but already provided by the standard library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/170)
> CollisionUtil: Replace FINDMINMAX macro with std::minmax()

- Runtime/Character/CCharacterInfo.cpp
- Runtime/Character/CCharacterInfo.hpp
Makes a few minor changes that potentially reduce the number of allocations necessary in certain scenarios by `std::move`-ing data that would otherwise heap allocate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/172)
> CCharacterInfo: Minor allocation related changes

- Runtime/MP1/World/CFlaahgraTentacle.cpp
GM8E v0 sets this to 0.04f.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/174)
> CFlaahgraTentacle: Amend floating point value within Play case in AcceptScriptMsg()

- Runtime/MP1/World/CFlaahgraTentacle.cpp
GM8E v0 does exactly this, so we can consider this double-checked ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/175)
> CFlaahgraTentacle: Remove FIXME comment in ShouldAttack()

- Runtime/World/CSnakeWeedSwarm.cpp
- Runtime/World/CSnakeWeedSwarm.hpp
- Runtime/World/ScriptLoader.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/176)
> Implement CSnakeWeedSwarm

- Runtime/Character/CBoneTracking.cpp
- Runtime/Character/CHierarchyPoseBuilder.hpp
- Runtime/Character/CIkChain.cpp
Previously this function was always returning by value, rather than by reference, like what its contained called function does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/184)
> CHierarchyPoseBuilder: Fix missing ampersand in CharLayoutInfo() return value

- Runtime/MP1/CInGameGuiManager.cpp
Allows us to eliminate some hardcoded array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/186)
> CInGameGuiManager: Make use of std::array where applicable

- Runtime/Graphics/CModelBoo.cpp
Gets rid of potential runtime-initializers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/189)
> CModelBoo: Make static data constexpr where applicable

- Runtime/CObjectList.cpp
- Runtime/CObjectList.hpp
- Runtime/GameObjectLists.cpp
- Runtime/GameObjectLists.hpp
None of the implementations modify object instance state, so this can be made const qualified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/191)
> CObjectList: Make IsQualified() a const member function

- Runtime/MP1/CLogBookScreen.cpp
This was temporarily added in for debugging purposes in the past but was never removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/200)
> CLogBookScreen: Remove unconditional return true in IsScanComplete()

- Runtime/Weapon/CPlayerGun.cpp
- Runtime/Weapon/CPlayerGun.hpp
- Make use of std::array where applicable
- Resolve implicit sign conversion warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/209)
> CPlayerGun: Minor cleanup

- Runtime/Particle/CDecalDataFactory.cpp
- Runtime/Particle/CDecalDataFactory.hpp
- Runtime/Particle/CParticleElectricDataFactory.cpp
- Runtime/Particle/CParticleElectricDataFactory.hpp
- Runtime/Particle/CParticleSwooshDataFactory.cpp
- Runtime/Particle/CParticleSwooshDataFactory.hpp
- Runtime/Particle/CProjectileWeaponDataFactory.cpp
- Runtime/Particle/CProjectileWeaponDataFactory.hpp
Same behavior, but with safer memory management.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/213)
> CProjectileWeaponDataFactory: Make GetGeneratorDesc() return a unique_ptr

- Runtime/AutoMapper/CAutoMapper.cpp
- Runtime/AutoMapper/CMapArea.cpp
- Runtime/AutoMapper/CMapArea.hpp
- Runtime/AutoMapper/CMapUniverse.cpp
- Runtime/AutoMapper/CMapWorld.cpp
- Runtime/AutoMapper/CMapWorldInfo.cpp
- Runtime/AutoMapper/CMapWorldInfo.hpp
- Runtime/CStateManager.cpp
Resolves trivial sign conversion warnings (and makes any implicit conversions explicit).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/217)
> AutoMapper/*: Resolve sign conversion warnings

- Runtime/AutoMapper/CMapArea.cpp
- Runtime/AutoMapper/CMapUniverse.cpp
- Runtime/CGameAllocator.cpp
- Runtime/CSaveWorld.cpp
- Runtime/Camera/CCameraManager.cpp
- Runtime/Character/CActorLights.cpp
- Runtime/Character/CAnimSource.cpp
- Runtime/Character/CBodyState.cpp
- Runtime/Graphics/CModelBoo.cpp
- Runtime/Graphics/CMoviePlayer.cpp
- Runtime/GuiSys/CHudRadarInterface.cpp
- Runtime/GuiSys/CTextRenderBuffer.cpp
- Runtime/Particle/CDecal.cpp
- Runtime/Particle/CElementGen.cpp
- Runtime/Weapon/CGrappleArm.cpp
- Runtime/World/CGameArea.cpp
- Runtime/World/CStateMachine.cpp
- Runtime/World/CWorld.cpp
Same behavior, but with less code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/218)
> Runtime: Collapse emplace_back() calls where applicable

- Runtime/CGameHintInfo.cpp
- Runtime/CGameHintInfo.hpp
Avoids trivial unnecessary copies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/223)
> CGameHintInfo: Take CVParamTransfer parameter by const reference

- Runtime/Character/CAnimSourceReader.cpp
Tidies up some code by making use of `emplace()` where applicable. We can also compress some loops into `std::find_if`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/227)
> CAnimSourceReader: Minor cleanup

- Runtime/MP1/CPauseScreenBase.cpp
- Mark colors as constexpr within UpdateSideTable()
- Make use of std::array in GetImagePaneName()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/230)
> CPauseScreenBase: Minor cleanup

- Runtime/Character/CPoseAsTransforms.cpp
- Runtime/Character/CPoseAsTransforms.hpp
Same behavior, but allows for less code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/233)
> CPoseAsTransforms: Make use of std::array where applicable 

- Runtime/Weapon/CGrappleArm.cpp
- Runtime/Weapon/CGrappleArm.hpp
- Resolve sign mismatch warnings in loops
- Move `skDependencyNames` into `BuildSuitDependencyList()`
- CGrappleArm: Convert `reinterpret_cast` to `static_cast` in `PointGenerator()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/236)
> CGrappleArm: Minor changes

- Runtime/AutoMapper/CMapArea.cpp
- Remove type-punning undefined behavior within PostConstruct()
- Resolve variable name shadowing
- Make use of std::array where applicable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/241)
> CMapArea: Minor changes

- Runtime/AutoMapper/CAutoMapper.cpp
- Runtime/AutoMapper/CAutoMapper.hpp
- Runtime/AutoMapper/CMapWorld.cpp
- Runtime/AutoMapper/CMapWorld.hpp
- Remove most usages of const_cast
- Provide parameter names in header for functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/242)
> CMapWorld: Minor changes

- Runtime/GuiSys/CGuiSliderGroup.hpp
Same behavior, stronger typing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/248)
> CGuiSliderGroup: Make use of std::array where applicable

- Runtime/CObjectList.hpp
Same behavior, but with stronger typing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/249)
> CObjectList: Make use of std::array where applicable

- Runtime/Input/CInputGenerator.hpp
- Runtime/Input/CRumbleGenerator.cpp
- Runtime/Input/CRumbleGenerator.hpp
Allows removing hardcoded array sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/251)
> CInputGenerator: Make use of std::array where applicable

- Runtime/CMemoryCardSys.cpp
- Runtime/CSaveWorld.cpp
- Runtime/GuiSys/CHudDecoInterface.cpp
- Runtime/GuiSys/CRasterFont.cpp
- Runtime/GuiSys/CTextParser.cpp
- Runtime/GuiSys/CTextRenderBuffer.cpp
- Runtime/Particle/CColorElement.cpp
- Runtime/Particle/CParticleElectric.cpp
- Runtime/Particle/CVectorElement.cpp
- Runtime/World/CGameArea.cpp
- Runtime/World/CScriptPickupGenerator.cpp
- Runtime/World/CScriptSpecialFunction.cpp
- Runtime/World/CScriptTrigger.cpp
Allows for in-place construction. Also results in less code to read in certain usages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/258)
> General: Make use of emplace_back where applicable

- Runtime/Particle/CParticleSwoosh.cpp
- Runtime/Particle/CParticleSwoosh.hpp
Resolves trivial warnings within loop condition checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/269)
> CParticleSwoosh: Resolve sign-conversion warnings

- Runtime/World/CPlayer.hpp
Makes them more self-documenting from the interface alone and also
allows IDEs to perform better parameter and argument inspection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/271)
> CPlayer: Add parameter names to prototypes

- Runtime/World/CEntity.hpp
- Runtime/World/CScriptCameraHint.cpp
- Add parameter names to interface 
- Rename ConnectionList() to GetConnectionList() for const overloading
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/277)
> CEntity: Minor changes

- Runtime/CToken.hpp
- Runtime/Character/CAllFormatsAnimSource.hpp
- Runtime/Character/CBodyStateCmdMgr.hpp
- Runtime/Character/CHierarchyPoseBuilder.hpp
- Runtime/Character/CRagDoll.hpp
- Runtime/Character/IAnimReader.hpp
- Runtime/MP1/World/CBabygoth.cpp
- Runtime/MP1/World/CChozoGhost.cpp
- Runtime/MP1/World/CFlaahgra.cpp
- Runtime/MP1/World/CFlyingPirate.cpp
- Runtime/MP1/World/CFlyingPirate.hpp
- Runtime/MP1/World/CJellyZap.cpp
- Runtime/MP1/World/CMetaree.cpp
- Runtime/MP1/World/CSpacePirate.cpp
- Runtime/MP1/World/CSpacePirate.hpp
- Runtime/Weapon/CBurstFire.hpp
- Runtime/Weapon/CProjectileInfo.hpp
- Runtime/World/CAi.hpp
- Runtime/World/CKnockBackController.hpp
- Runtime/World/CPatterned.hpp
- Runtime/World/ScriptLoader.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axiodl/urde/254)
> CFlyingPirate implementation

- Runtime/GuiSys/CTextRenderBuffer.cpp
- Runtime/GuiSys/CTextRenderBuffer.hpp
Reverts AxioDL/urde#282
Sadly this breaks building, I should have tested but it seemed like an overall benign change.
> Revert "CTextRenderBuffer: Forward declare structs where applicable"

- Runtime/GuiSys/CTextRenderBuffer.cpp
- Runtime/GuiSys/CTextRenderBuffer.hpp
This reverts commit 16745f3a7b17c483a03900eb527b844603ae5473.
We can simply default the move constructor and move assignment operator to make this work.
> Revert "Revert "CTextRenderBuffer: Forward declare structs where applicable"

- Runtime/CToken.hpp
This should be returning by reference, not the pointer of this.
> CToken: Amend incorrect return value of TToken's operator=

- Runtime/GameObjectLists.cpp
- Runtime/MP1/CSamusHud.cpp
- Runtime/MkCastTo.py
- Runtime/World/CPlayer.cpp
Prevents error prone implicit conversions.
> MkCastTo: Make operator bool instances explicit

- Runtime/Collision/CCollisionInfo.hpp
- Runtime/Collision/CCollisionInfoList.hpp
- Runtime/Particle/CElementGen.hpp
- Runtime/Particle/CParticleSwoosh.hpp
- Runtime/Particle/CUVElement.cpp
- Runtime/Weapon/CNewFlameThrower.cpp
- Runtime/Weapon/CNewFlameThrower.hpp
- Runtime/World/CSnakeWeedSwarm.hpp
Current bugs:
- Lights don't light
- Some particles are rendered over one another (secondary smoke & main flames)
- Rendering of particles doesn't match original version, original sorted all particles together (so rendering would be interleaved), contributing to the above bug
- MainSmoke particles move too fast, original seemed to have damped movement that stopped before despawning.
> Flamethrower weapon implementation

- Runtime/MP1/World/CMetroidPrimeEssence.cpp
- Runtime/Particle/CElementGen.cpp
- Runtime/Particle/CElementGen.hpp
- Runtime/Weapon/CNewFlameThrower.cpp
Properly handle allocation of particles and ADV parameters.
> Particle fixes

- Editor/ProjectManager.cpp
- Editor/Space.hpp
- Editor/SplashScreen.cpp
- Editor/ViewManager.cpp
- Editor/main.cpp
- Runtime/AutoMapper/CMapArea.cpp
- Runtime/CFactoryMgr.cpp
- Runtime/CMakeLists.txt
- Runtime/CResFactory.cpp
- Runtime/CStateManager.cpp
- Runtime/Character/CAnimData.cpp
- Runtime/Character/CSkinRules.cpp
- Runtime/Graphics/CBooRenderer.cpp
- Runtime/Graphics/CGraphics.cpp
- Runtime/Graphics/CGraphics.hpp
- Runtime/Graphics/CLineRenderer.cpp
- Runtime/Graphics/CModelBoo.cpp
- Runtime/Graphics/CSkinnedModel.cpp
- Runtime/Graphics/Shaders/CFluidPlaneShader.cpp
- Runtime/Particle/CDecalManager.cpp
- Runtime/Particle/CElementGen.cpp
- Runtime/Weapon/CGunWeapon.cpp
- Runtime/World/CFluidPlane.cpp
- Runtime/World/CFluidPlaneCPU.cpp
Requires boo change (https://github.com/AxioDL/boo/pull/44).
> Using optick, linked from boo

- Runtime/ImGuiConsole.cpp
- Runtime/ImGuiConsole.hpp
- Runtime/World/CWorld.cpp
- Runtime/World/CWorld.hpp
> Add imgui layer editor

- DataSpec/SpecBase.cpp
- DataSpec/SpecMP1.cpp
- DataSpec/SpecMP2.cpp
- DataSpec/SpecMP3.cpp
- hecl/driver/ToolImage.hpp
- hecl/include/hecl/MultiProgressPrinter.hpp
- hecl/lib/ClientProcess.cpp
- hecl/lib/MultiProgressPrinter.cpp
- hecl/lib/Project.cpp
Also fixes the SpecMP1/2/3 using string_view instead of SystemStringView
> Use StringView in MultiProgressPrinter

- README.md
Build Prerequisites: Added Fedora packages
> Add Fedora packages to README

- Runtime/Weapon/CWaveBuster.cpp
- Runtime/Weapon/CWaveBuster.hpp
This isn't 100%, lots of unnamed vars still. Didn't re-reverse several functions either, only focused on getting rendering to work.
> Fixed wavebuster rendering, plus tiny targeting preference (issue?)

- Runtime/Weapon/CWaveBeam.cpp
> x24c_effectTimer wasn't counted down

- Runtime/Particle/CElementGen.cpp
> x280_VELSources and x278_hasVMD don't skip indices
